version: '3.8'

services:
  test-deploy:
    build:
      context: .
      dockerfile: Dockerfile
    # command: pulumi refresh --stack=stage --skip-preview
    command: sleep 100000
    # command: /code/infra/scripts/test-deploy.sh
    env_file:
      - .env
    volumes:
      - ..:/code/
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /code/infra
    platform: linux/amd64
